### ISSUE TITLE
Style React Template to look like minimal viewer. 

### ISSUE THREAD

**Issue by phtaylor** [ZeaInc/zea-react-template#7]
Header with logo in top left.

darker colors.

![image](https://user-images.githubusercontent.com/840121/144999124-1cd0ef83-31d6-459b-898f-6657d0ae00a8.png)

**Comment by mauroporras** [comment]
(Add screenshot here once it's done).

**Comment by mauroporras** [comment]
<img width="1780" alt="Screen Shot 2021-12-08 at 15 34 47" src="https://user-images.githubusercontent.com/167700/145280434-b999add4-744a-4c04-9d08-d13b67c4c56f.png">
